name: container-release

trigger:
  on_push:
    tags: ["v*"]

needs_flake:
  - packages.containerImage

steps:
  - name: push
    env: .moira/envs/container.nix
    run: |
      skopeo copy --policy .containers-policy.json \
        --dest-creds "$REGISTRY_USER:$REGISTRY_PASS" \
        docker-archive:${{ flake.packages.containerImage }} \
        "docker://git.hydrar.de/jmarya/terrarium:${MOIRA_COMMIT_TAG}"
    secrets:
      - REGISTRY_USER
      - secret: REGISTRY_PASS
        env: REGISTRY_PASS
    network: true
