when:
  event: ["push", "pull_request"]
  branch: main

steps:
  - name: Rust Tests
    image: rust:latest
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - rustup default nightly
      - cargo check -j 4
      - cargo test -j 4 --all-features
